package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.Navigation;

import java.util.List;

public interface NavigationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATIONS
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATIONS
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    int insert(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATIONS
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    int insertSelective(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATIONS
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    Navigation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATIONS
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    int updateByPrimaryKeySelective(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATIONS
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    int updateByPrimaryKey(Navigation record);

    List<Navigation> selectByStatus(Integer status);
}