package com.bt.shopguide.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Navigation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.id
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.name
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.text
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.url
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.fetch_new
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private Integer fetchNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.status
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.seq
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.create_time
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAVIGATIONS.update_time
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.id
     *
     * @return the value of NAVIGATIONS.id
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.id
     *
     * @param id the value for NAVIGATIONS.id
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.name
     *
     * @return the value of NAVIGATIONS.name
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.name
     *
     * @param name the value for NAVIGATIONS.name
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.text
     *
     * @return the value of NAVIGATIONS.text
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.text
     *
     * @param text the value for NAVIGATIONS.text
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.url
     *
     * @return the value of NAVIGATIONS.url
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.url
     *
     * @param url the value for NAVIGATIONS.url
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.fetch_new
     *
     * @return the value of NAVIGATIONS.fetch_new
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public Integer getFetchNew() {
        return fetchNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.fetch_new
     *
     * @param fetchNew the value for NAVIGATIONS.fetch_new
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setFetchNew(Integer fetchNew) {
        this.fetchNew = fetchNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.status
     *
     * @return the value of NAVIGATIONS.status
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.status
     *
     * @param status the value for NAVIGATIONS.status
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.seq
     *
     * @return the value of NAVIGATIONS.seq
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.seq
     *
     * @param seq the value for NAVIGATIONS.seq
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.create_time
     *
     * @return the value of NAVIGATIONS.create_time
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.create_time
     *
     * @param createTime the value for NAVIGATIONS.create_time
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAVIGATIONS.update_time
     *
     * @return the value of NAVIGATIONS.update_time
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAVIGATIONS.update_time
     *
     * @param updateTime the value for NAVIGATIONS.update_time
     *
     * @mbggenerated Tue Jan 09 10:45:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}